[project]
name = 'Blockchain-Circular-Economy-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-listing]
path = 'contracts/material-listing.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-quality]
path = 'contracts/material-quality.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
